version: '3.9'
services:
    nginx-proxy:
        image: nginxproxy/nginx-proxy
        container_name: nginx-proxy
        restart: always
        environment:
            ENABLE_IPV6: 1
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./conf:/etc/nginx/conf.d
            - ./vhost:/etc/nginx/vhost.d
            - ./html:/usr/share/nginx/html
            - ./dhparam:/etc/nginx/dhparam
            - ./certs:/etc/nginx/certs:ro
            - /var/run/docker.sock:/tmp/docker.sock:ro

    nginx-proxy-acme:
        image: nginxproxy/acme-companion
        container_name: nginx-proxy-acme
        restart: always
        links:
            - nginx-proxy
        volumes:
            - ./vhost:/etc/nginx/vhost.d
            - ./html:/usr/share/nginx/html
            - ./dhparam:/etc/nginx/dhparam
            - ./certs:/etc/nginx/certs:rw
            - /var/run/docker.sock:/var/run/docker.sock:ro
        environment:
            NGINX_PROXY_CONTAINER: nginx-proxy

    proxy-companion:
        container_name: proxy-companion
        restart: always
        image: sebastienheyd/self-signed-proxy-companion
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./certs:/etc/nginx/certs:rw

    mailcatcher:
        container_name: mailcatcher
        image: sj26/mailcatcher
        restart: unless-stopped
        ports:
          - "1080:1080"

    opensearch:
        container_name: opensearch
        build:
          dockerfile: Dockerfile
          context: images/opensearch
        restart: unless-stopped
        ports:
          - "9200"
          - "9300"
        env_file: env/opensearch.env
        environment:
          - "discovery.type=single-node"
          - "cluster.routing.allocation.disk.threshold_enabled=false"
          - "index.blocks.read_only_allow_delete"
          - "OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx2g"
          #- "max_map_count=262144"

    phpmyadmin:
        container_name: phpmyadmin
        image: linuxserver/phpmyadmin
        env_file: env/phpmyadmin.env
        ports:
            - "8080:80"
        networks:
            - shared-db-network

networks:
    default:
        external: true
        name: nginx-proxy
    shared-db-network:
        external: true
